package com.rigsec.lotteranalsis.dbdata;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.rigsec.lotteranalsis.dbdata.BasicHistroyData;

import com.rigsec.lotteranalsis.dbdata.BasicHistroyDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig basicHistroyDataDaoConfig;

    private final BasicHistroyDataDao basicHistroyDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        basicHistroyDataDaoConfig = daoConfigMap.get(BasicHistroyDataDao.class).clone();
        basicHistroyDataDaoConfig.initIdentityScope(type);

        basicHistroyDataDao = new BasicHistroyDataDao(basicHistroyDataDaoConfig, this);

        registerDao(BasicHistroyData.class, basicHistroyDataDao);
    }
    
    public void clear() {
        basicHistroyDataDaoConfig.clearIdentityScope();
    }

    public BasicHistroyDataDao getBasicHistroyDataDao() {
        return basicHistroyDataDao;
    }

}
